{
 "title": "API Response Time and Traffic",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "API Requests Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{queried_path=~\"/user|/task\"}[30m])) by (queried_path)"
    }
   ]
  },
  { "title": "API Average response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average Response Time of Task API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_sum{queried_path=~\"^/task*\"}[5m]))/avg(rate(http_request_duration_seconds_count{queried_path=~\"^/task*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Average Response Time of User API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_sum{queried_path=~\"^/user*\"}[5m]))/avg(rate(http_request_duration_seconds_count{queried_path=~\"^/user*\"}[5m]))"
    }
   ]
  }
 ]
}