apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http  # Name for the application port
      protocol: TCP
      port: 80          # This is the port that will be exposed externally
      targetPort: 8081  # This is the application port on the pod
    - name: metrics  # Name for the metrics port
      protocol: TCP
      port: 8080       # This is the port that Prometheus will scrape
      targetPort: 8080  # This should match the metrics endpoint in your application
  type: LoadBalancer