apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: default
spec:
  selector:
    app: postgres
    component: postgres-exporter
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187