apiVersion: v1
kind: Service
metadata:
  name: task-manager
spec:
  selector:
    app: task-manager
  ports:
  - name: http
    protocol: TCP
    port: 8082
    targetPort: 8082
  - name: metrics  
    protocol: TCP
    port: 8080      
    targetPort: 8080
  type: ClusterIP