apiVersion: v1
kind: Service
metadata:
  name: user-manager
spec:
  selector:
    app: user-manager
  ports:
  - name: http
    protocol: TCP
    port: 8083
    targetPort: 8083
  - name: metrics  
    protocol: TCP
    port: 8080      
    targetPort: 8080
  type: ClusterIP